Repository sa-tre/satre-specification, pull requests merged in 2023-06, with the labels that each got.

#81 Add one sentence for each capability
  docs/source/standard.md
Labels: documentation, proposed change

#83 Add information security section to draft specification
  docs/source/standard.md
Labels: documentation, proposed change, WP1

#86 Information governance capabilities
  docs/source/standard.md
Labels: documentation, proposed change, WP1

#82 first draft of walkthrough doc
  docs/Walkthrough.md
  docs/images/.DS_Store
  docs/images/Code_page.png
  docs/images/GH_homepage.png
  docs/images/Issue_comment.png
  docs/images/Issue_tag.png
  docs/images/Issues.png
  docs/images/New_issue.png
  docs/images/Notifications_repo.png
  docs/images/Notifications_settings.png
  docs/images/PR.png
  docs/images/PR_comment.png
  docs/images/SATRE-CC-Registration.png
  docs/images/SATRE-Github-Issues.png
  docs/images/SATRE-fork.png
  docs/images/Specification_repo.png
  docs/images/read_the_docs.png
  docs/images/settings.png
Labels: WP5

#84 Add data management section
  docs/source/standard.md
Labels: documentation, proposed change, WP1

#91 Add infrastructure lifecycle and availability sections
  docs/source/standard.md
Labels: documentation, proposed change, WP1

#94 Add a `Mandatory?` column to all tables
  docs/source/standard.md
Labels: documentation, proposed change, WP1

#106 Restructure introduction to specification
  docs/images/.DS_Store
  docs/images/Architecture.svg
  docs/images/Capability_Map.svg
  docs/source/conf.py
  docs/source/standard.md
Labels: proposed change

#100 added information on satre team contributions on behalf of community
  docs/source/contributing.md
Labels: governance

#108 Re-order documentation
  .gitignore
  docs/source/index.md
  docs/source/pillars/computing_technology.md
  docs/source/pillars/data_management.md
  docs/source/pillars/information_governance.md
  docs/source/pillars/supporting.md
  docs/source/specification.md
  docs/source/standard.md
Labels: proposed change

#115 Capability map update - spec v0.2 candidate
  docs/images/Capability_Map.svg
  docs/images/Capability_Map/full.drawio.svg
  docs/source/index.md
  docs/source/pillars/computing_technology.md
  docs/source/pillars/data_management.md
  docs/source/pillars/information_governance.md
  docs/source/pillars/supporting.md
  docs/source/specification.md
Labels: WP1

#122 Add SSO login as an optional under the Identity and access management capability
  docs/source/pillars/data_management.md
Labels: proposed change, WP1, pillar: data management

#124 Update version of `sphinx_rtd_theme`
  docs/requirements.txt
Labels: bug

#127 Remove horizontal scrollbar from tables and return to previous format
  docs/source/_templates/layout.html
Labels: bug
