Repository sa-tre/satre-specification, pull requests merged in 2023-05, with the labels that each got.

#35 Migrate document to readthedocs
  .readthedocs.yaml
  docs/README.md
  docs/requirements.in
  docs/requirements.txt
Labels: WP1

#40 Remove gh pages
  .github/workflows/documentation.yml
  README.md
Labels: WP1

#48 Update the issue templates to account for source of issue
  .github/ISSUE_TEMPLATE/change.yml
  .github/ISSUE_TEMPLATE/discussion.yml
  .github/ISSUE_TEMPLATE/governance.yml
Labels: governance

#71 Add the skeleton of a capability-based layout
  docs/source/conf.py
  docs/source/contributing.md
  docs/source/evaluation.md
  docs/source/index.md
  docs/source/standard.md
Labels: documentation, WP1

#77 Add pre-commit for linting/autoformatting
  .github/pull_request_template.md
  .github/workflows/documentation.yml
  .pre-commit-config.yaml
  .prettierignore
  .readthedocs.yaml
  CODE_OF_CONDUCT.md
  README.md
  docs/README.md
  docs/source/_templates/footer.html
  docs/source/contributing.md
  docs/source/standard.md
Labels: request review
