Repository sa-tre/satre-specification, pull requests merged in 2023-09, with the labels that each got.

#232 Fix evaluation scores definition list
  docs/source/evaluation.md
Labels: bug

#231 Add an evaluation spreadsheet
  .github/workflows/documentation.yml
  .gitignore
  .readthedocs.yaml
  docs/Makefile
  docs/extensions/__init__.py
  docs/extensions/satrecsv.py
  docs/requirements.in
  docs/requirements.txt
  docs/source/conf.py
  docs/source/evaluation.md
Labels: WP1, python

#211 Add TRE roles
  README.md
  docs/source/evaluations/alan_turing_institute.md
  docs/source/glossary.md
  docs/source/index.md
  docs/source/pillars/computing_technology.md
  docs/source/pillars/data_management.md
  docs/source/pillars/information_governance.md
  docs/source/pillars/supporting.md
  docs/source/roles.md
  docs/source/specification.md
Labels: proposed change, WP1

#242 Address HDR UK comments - issue 206
  docs/source/pillars/data_management.md
  docs/source/pillars/supporting.md
Labels: proposed change, WP1, pillar: data management, pillar: supporting

#251 Invalid use of `Required` Importance, should be `Mandatory`
  docs/source/pillars/computing_technology.md
Labels: bug, pillar: computing technology

#247 Update contact list in walkthrough
  docs/source/contributing/walkthrough.md
Labels: WP1

#252 Increase clarity on SATRE purpose, how and why to use the spec and evaluation
  docs/source/evaluation.md
  docs/source/faqs.md
  docs/source/glossary.md
  docs/source/index.md
  docs/source/specification.md
Labels: proposed change, WP1, collaboration cafe
