Repository sa-tre/satre-specification, pull requests merged in 2023-10, with the labels that each got.

#264 Rewrite front-page to be more relevant to readers, ensure there's an entrypoint to the specification content
  docs/source/conf.py
  docs/source/evaluation.md
  docs/source/index.md
  docs/source/specification.md
Labels: proposed change, WP1

#263 Add definition of capacity management
  docs/source/pillars/computing_technology.md
Labels: WP1, pillar: computing technology

#261 FAQ: other TRE archetypes and data tiers
  docs/source/faqs.md
Labels: proposed change, WP1

#273 Recommend public reporting of incidents and near misses
  docs/source/pillars/supporting.md
Labels: WP5, proposed change, pillar: supporting

#269 Move information security to computing technology
  docs/images/Capability_Map/full.drawio.svg
  docs/source/pillars/computing_technology.md
  docs/source/pillars/data_management.md
Labels: WP1, pillar: computing technology, pillar: data management

#271 Turing eval extra data management & information security statements
  docs/source/evaluations/alan_turing_institute.md
  docs/source/pillars/computing_technology.md
Labels: pillar: data management

#289 3.3.8: output checks can't control what's submitted to them
  docs/source/pillars/data_management.md
Labels: pillar: data management

#291 Add responsible disclosure text for near miss reporting
  docs/source/pillars/supporting.md
Labels: proposed change, WP1, pillar: supporting

#294 Add Turing eval answer for statement 4.8.4
  docs/source/evaluations/alan_turing_institute.md
Labels: pillar: supporting

#276 Update public trust principle
  docs/source/principles.md
Labels: WP1

#295 Use consistent path for downloadable satre.xlsx spreadsheet
  .readthedocs.yaml
  docs/Makefile
  docs/generated/.gitignore
  docs/source/conf.py
  docs/source/evaluation.md
Labels: bug

#292 Scoring: Use N/A for recommended/optional, 0 is only a failure for Mandatory
  docs/source/evaluation.md
Labels: proposed change

#293 Add page linking to external architecture doc
  docs/images/architecture-metamodel.jpg
  docs/source/architecture.md
  docs/source/index.md
Labels: WP1

#296 Updates index.html based on #278 proposal
  docs/source/index.md
Labels: WP1

#301 Adjust Turing Data Safe Haven description
  docs/source/conf.py
  docs/source/evaluations/alan_turing_institute.md
Labels: WP1
